ARDUINO_DIR = /home/atomsfat/java/arduino-1.0
PARSE_BOARD = /home/atomsfat/Workspace/Arduino-Makefile/arduino-mk/ard-parse-boards

BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = LPD6803 EasyTransfer TimmerOne

AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf

include /home/atomsfat/Workspace/Arduino-Makefile/arduino-mk/Arduino.mk
