ARDUINO_DIR = /home/atomsfat/java/arduino-1.0
PARSE_BOARD = /home/atomsfat/Workspace/Arduino-Makefile/arduino-mk/ard-parse-boards

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB1

ARDUINO_LIBS = Ethernet Ethernet/utility EasyTransfer SPI

AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf

include /home/atomsfat/Workspace/Arduino-Makefile/arduino-mk/Arduino.mk
